#!/usr/bin/perl

# 1. Scalar

# test string
my $text="abc";
print "text = $text\n";

# test integer
my $number=123;
print "number = $number\n";

# test float
my $ff=2.3456;
print "ff = $ff\n";

print "\n\n\n";
# 2. Scalar array
my @array1=qw(a b c d);

# print
#print "array1[0] = $array1[0]\n";
#print "array1[1] = $array1[1]\n";
#print "array1[2] = $array1[2]\n";
#print "array1[3] = $array1[3]\n";

# use for print
for($i = 0; $i <= $#array1; $i++) {
  print "array1[$i] = $array1[$i]\n";
}

print "\n\n\n";
# 3. Hash Array
my %hash1=("i1"=>"aaa","i2"=>"bbb","i3"=>"ccc");
#my %hash1=("i1","aaa","i2","bbb","i3","ccc");

#$hash1{'i1'}="aaa";
#$hash1{'i2'}="bbb";
#$hash1{'i3'}="ccc";

# print
#print "hash1{'i1'} = $hash1{'i1'}\n";
#print "hash1{'i2'} = $hash1{'i2'}\n";
#print "hash1{'i3'} = $hash1{'i3'}\n";

# print use foreach
foreach $key (keys %hash1) {
  print "hash1[$key] = $hash1{$key}\n";
}

print "\n\n\n";
# 4. References(Pointer)
