#!/usr/bin/perl

# 1. Conditional Control Statements
#my $name="friend";
#my $name="ok";

#print "HELLO!\n" if ($name eq "friend");
if($name eq "friend"){
  print "name = friend\n"
}elsif($name eq "ok"){
  print "name = ok\n"
}else{
  print "name = null\n"
}

print "\n\n\n";
# 2. Loop Control Statements
# for test
#for($i=0; $i<=10; $i++) {
#  print "i = $i\n";
#}

# foreach test
#my @array=qw(a b c d);
#foreach $i (@array) {
#  print "i = $i\n";
#}

# for(精簡) test
#for $i (0..5) {
#  print "i = $i\n";
#}

# while test
#my $i=0;
#while($i<15) {
#  $i=$i+1;
#  print "i = $i\n";
#}

# do while test
#my $i=0;
#do {
#  $i=$i+1;
#  print "i = $i\n";
#} while( $i < 20);

# while test(break, continue)
my $i=0;
while($i<15) {
  $i=$i+1;

  # continue 5, 10, 15
  next if ($i == 5);
  next if ($i == 10);
  next if ($i == 15);

  # if $i > 12 break
  last unless ($i <= 12);

  # print $i
  print "i = $i\n";
}
