#!/usr/bin/perl

sub Po_test1{
  # 1. open and read the file
  print "call Po_test1()\n";
  my $filename="./Po_test_file";
  open(FILE, $filename) || die "Can't open file $filename : $!\n";

  # read file
  #while($_=<FILE>){
  #  print "$_";
  #}
  print while(<FILE>);
  close(FILE);
}

sub Po_clear{
  print "\n\n\n";
}

sub Po_test2{
  # 2. input test
  print "call Po_test2()\n";

  $input=<STDIN>;
  chomp $input;
  if($input == 123){
    print "you scan 123\n";
  }else{
    print "please input 123\n";
  }
}

&Po_test1

&Po_test2
Po_clear

