#!/usr/bin/perl

sub Po_test1{
  my @numbers = (1..5);
  print "numbers = @numbers\n";       # 1 2 3 4 5
  my @doubles = map {$_ * 2} @numbers;
  print "doubles = @doubles\n";       # 2 4 6 8 10
}

sub Po_test2{
  @user= ('s99639118', 's99639119', 's99639120', 's99639121');
  print "user = @user\n";
  @mail = map {  $_ .  '@stu.edu.tw' } @user;
  print "mail = @mail\n";
}

sub Po_test3{
  @m=("   www",  "facility ", " mail ");
  print "(origin) m = @m\n";
  map { s/\s+//g } @m;    # 1. \s 其實就是 [ \t\n], "任何一個空白類字元"  2. + 重複出現任意次, 至少 1 次
  print "(modify) m = @m\n";
}

&Po_test1
&Po_test2
&Po_test3
